version: '3.8'
services:
  app:
    container_name: app
    build: 
      context: ./backend
    depends_on:
      - db
    ports:
      - "${BACKEND_EXTERNAL_PORT}:8080"
    environment:
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - SPRING_DATASOURCE_URL=${DATABASE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}

  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: "${DATABASE_USERNAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - "${DATABASE_EXTERNAL_PORT}:5432"
    volumes:
      - ./data:/var/lib/postgresql/data