version: '3.8'
services:
  app:
    container_name: app
    build: 
      context: .
    depends_on:
      - db
    ports:
      - "8081:8080"
    environment:
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/allevents
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data